### PR TITLE
💅 Code style improvements

### PR DESCRIPTION
**Pull request by diegocrzt**
- Adds prettier with its configuration, 
- Reformat the code to comply with TSLint suggestions
- Refactor some components to follow Angular Code style guidelines.

Signed-off-by: Diego Ramírez <diegocrzt@gmail.com>

### CODE REVIEW

**Comment by diegocrzt** [comment]
What do you think @Zalimben  ?

**Comment by viktor992** [comment]
Good job, CarpinchE! :nail_care:

**Comment by diegocrzt** [comment]
What do you think @Zalimben  ?

**Review by Zalimben — APPROVED** [review]
Code review: :+1: 
Functionality: :+1: 
Verified!

**Pull request merged**
